FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./

ENV HUSKY_SKIP_INSTALL=1
ENV HUSKY=0

RUN npm install --omit=dev

COPY . .

RUN npm run build

FROM node:20-alpine AS production

WORKDIR /usr/src/app

COPY package*.json ./

ENV HUSKY_SKIP_INSTALL=1
RUN npm install --production

COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 28000

CMD ["npm", "start"]
